name: Test build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      uses: vgaidarji/android-github-actions-build@v1.0.1
      with:
        args: ./gradlew test
